---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: worker-example
  namespace: test
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: worker-example
      sigs.k8s.io/cluster-api-cluster: tb-asg-35
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: worker-example
        sigs.k8s.io/cluster-api-cluster: tb-asg-35
        sigs.k8s.io/cluster-api-machine-role: infra
        sigs.k8s.io/cluster-api-machine-type: worker
    spec:
      providerConfig:
        value:
          apiVersion: libvirtproviderconfig/v1alpha1
          kind: LibvirtMachineProviderConfig
          domainMemory: 2048
          domainVcpu: 1
          ignKey: /var/lib/libvirt/images/worker.ign
          volume:
            poolName: default
            baseVolumeID: /var/lib/libvirt/images/coreos_base
            volumeName: worker-example
          networkInterfaceName: tectonic
          networkInterfaceHostname: worker-example
          networkInterfaceAddress: 192.168.124.12
          autostart: false
          uri: qemu+tcp://10.80.94.1/system
      versions:
        kubelet: ""
        controlPlane: ""
